// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClnvXSL9S3Y8CsM8SpfjIDr2pKNfL9Pxs',
    appId: '1:823209466542:web:acf157130015afc0fc2b3f',
    messagingSenderId: '823209466542',
    projectId: 'fluttercontactapp-bd165',
    authDomain: 'fluttercontactapp-bd165.firebaseapp.com',
    storageBucket: 'fluttercontactapp-bd165.appspot.com',
    measurementId: 'G-GN0REFH3B2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9MF1DufIpOEQO_4uuaZ1smllapZvONuE',
    appId: '1:823209466542:android:f3eef822950a3041fc2b3f',
    messagingSenderId: '823209466542',
    projectId: 'fluttercontactapp-bd165',
    storageBucket: 'fluttercontactapp-bd165.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF6wfxWMYnaG0gOqz63luDOLITLXaqs6c',
    appId: '1:823209466542:ios:882ae4a5b899d136fc2b3f',
    messagingSenderId: '823209466542',
    projectId: 'fluttercontactapp-bd165',
    storageBucket: 'fluttercontactapp-bd165.appspot.com',
    iosBundleId: 'com.example.flutterDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF6wfxWMYnaG0gOqz63luDOLITLXaqs6c',
    appId: '1:823209466542:ios:882ae4a5b899d136fc2b3f',
    messagingSenderId: '823209466542',
    projectId: 'fluttercontactapp-bd165',
    storageBucket: 'fluttercontactapp-bd165.appspot.com',
    iosBundleId: 'com.example.flutterDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClnvXSL9S3Y8CsM8SpfjIDr2pKNfL9Pxs',
    appId: '1:823209466542:web:f899ca353f4352e3fc2b3f',
    messagingSenderId: '823209466542',
    projectId: 'fluttercontactapp-bd165',
    authDomain: 'fluttercontactapp-bd165.firebaseapp.com',
    storageBucket: 'fluttercontactapp-bd165.appspot.com',
    measurementId: 'G-D5Z1CFGFKL',
  );
}
